# Generated by Django 2.2.6 on 2020-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200807_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_book_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friends', to='p_library.Friend'),
        ),
    ]
